image:
  file: .gitpod.Dockerfile

tasks:
    - name: App
      init: |
          yarn install
          gp env "EXPO_PACKAGER_PROXY_URL=$(gp url 8081)"
          eval $(gp env -e)
      command: yarn start -- --go

ports:
    - port: 8081
      visibility: public
      onOpen: ignore
    - port: 6080
      visibility: public
      onOpen: ignore

vscode:
    extensions:
        - esbenp.prettier-vscode
        - dbaeumer.vscode-eslint
        - caponetto.vscode-diff-viewer
        - eamodio.gitlens
